import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import MarkdownRenderer from "@/components/ui/markdown-renderer";

interface BriefData {
  id: string;
  title: string;
  event_description: string;
  content: string;
  created_at: string;
  expires_at: string;
}

export default function StrategyBriefPage() {
  const { id } = useParams<{ id: string }>();
  const [brief, setBrief] = useState<BriefData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    (async () => {
      const { data, error: err } = await (supabase as any)
        .from("ai_strategy_briefs")
        .select("id, title, event_description, content, created_at, expires_at")
        .eq("id", id)
        .single();

      if (err || !data) {
        setError("This strategy brief was not found or has expired.");
        setLoading(false);
        return;
      }

      // Check expiration
      if (data.expires_at && new Date(data.expires_at) < new Date()) {
        setError("This strategy brief has expired.");
        setLoading(false);
        return;
      }

      setBrief(data as BriefData);
      setLoading(false);
    })();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-[#1e3a5f]" />
      </div>
    );
  }

  if (error || !brief) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center px-4">
        <div className="text-center max-w-md">
          <div className="w-16 h-16 rounded-full bg-gray-100 flex items-center justify-center mx-auto mb-4">
            <span className="text-2xl">🔗</span>
          </div>
          <h1 className="text-xl font-bold text-gray-900 mb-2">Brief Unavailable</h1>
          <p className="text-gray-500 text-sm">
            {error || "This strategy brief was not found or has expired."}
          </p>
          <a href="https://milcrunch.com" className="inline-block mt-6 text-[#1e3a5f] text-sm font-medium hover:underline">
            Visit MilCrunch →
          </a>
        </div>
      </div>
    );
  }

  const createdDate = new Date(brief.created_at).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  return (
    <div className="min-h-screen bg-[#FAFAFA]">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-3xl mx-auto px-6 py-5 flex items-center justify-between">
          <span className="text-lg font-bold text-gray-900 tracking-tight">
            MilCrunch<span className="text-[#3b82f6] font-extrabold">X</span>
          </span>
          <span className="text-xs text-gray-400">AI Strategy Brief</span>
        </div>
      </header>

      {/* Title bar */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-3xl mx-auto px-6 py-6">
          <h1 className="text-2xl font-extrabold text-gray-900 mb-1">{brief.title || "Strategy Brief"}</h1>
          <p className="text-sm text-gray-500">
            Generated {createdDate}
          </p>
          {brief.event_description && (
            <p className="text-sm text-gray-600 mt-3 leading-relaxed">{brief.event_description}</p>
          )}
          <div className="mt-4 h-1 w-16 rounded-full bg-[#1e3a5f]" />
        </div>
      </div>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-8">
        <div className="bg-white rounded-xl border border-gray-200 p-8 shadow-sm">
          <MarkdownRenderer content={brief.content} className="text-[15px]" />
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 bg-white mt-12">
        <div className="max-w-3xl mx-auto px-6 py-6 text-center">
          <p className="text-xs text-gray-400">
            Generated by{" "}
            <a href="https://milcrunch.com" className="text-[#1e3a5f] hover:underline font-medium">
              MilCrunchX AI
            </a>{" "}
            — milcrunch.com
          </p>
          <p className="text-[10px] text-gray-300 mt-1">
            This brief expires {new Date(brief.expires_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </p>
        </div>
      </footer>
    </div>
  );
}
